### ISSUE TITLE
Token exceeded for Nomic Embedding API usage

### ISSUE THREAD

**Issue by Deeparani95-Developer** [descentis/lab-code#10]
Hi,

I am getting below error when executing my changes. It seems free token was exceeded.

**Exception: (400, '{"detail":"You have exceeded your 1000000 free tokens of Nomic Embedding API usage. Enter a payment method at https://atlas.nomic.ai to continue with usage-based billing."}')**

Do I need to use different Embedding API? Kindly confirm.

Thanks..

**Comment by viveknkuvar** [comment]
Hi @Deeparani95-Developer ,
I also faced the same issue after exceeding token usage, you can try "all-MiniLM-L6-v2" for text embedding 
reference = https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
how to use = https://api.python.langchain.com/en/latest/embeddings/langchain_community.embeddings.huggingface.HuggingFaceEmbeddings.html

**Comment by descentis** [comment]
You can also try OpenAI embedding models. 
https://platform.openai.com/docs/guides/embeddings

**Comment by Deeparani95-Developer** [comment]
Hi Amit, Vivek,

Thanks for your reply. Now its working as expected.
