### ISSUE TITLE
Getting error while launching Web App in Azure Open AI

### ISSUE THREAD

**Issue by PrachiKashid** [descentis/lab-code#5]
Getting error while launching Web App in Azure Open AI
![issue in AzureAI](https://github.com/user-attachments/assets/01f521b1-cbac-4130-847e-f996e5abb322)

**Comment by descentis** [comment]
It usually happens the first few times. Please try reconnecting again. Let us know if the issue is still present

**Comment by PrachiKashid** [comment]
Issue got resolved
