### ISSUE TITLE
while solving lab 5, unable to get hyperlink with image

### ISSUE THREAD

**Issue by rohit02orion** [descentis/lab-code#7]
Hi Amit, I tried solving the lab 5 assignment and deployed the dall-e-3 model as per instruction give in lab, but I am not able to get desired hyperlink with image after giving prompt. I had attached the screenshot for your reference.

![image](https://github.com/user-attachments/assets/626af405-8d9b-4025-922f-3589faf5210b)

**Comment by rohit02orion** [comment]
It is print the Exception in terminal as it shown in screenshot.

**Comment by Yogesh-orioninc** [comment]
Hi @rohit02orion , 

Please take a look at this line:

`url = "{}openai/deployments/dalle3/images/generations?api-version={}".format(api_base, api_version)`

Make sure to update the model name to match what you've configured in Azure Studio.

I hope this helps resolve the issue!
