### ISSUE TITLE
Unable to push code - 403: Permission  Error

### ISSUE THREAD

**Issue by chandarg75** [descentis/lab-code#9]
I am getting 403 permission error, when I tried to push my code:

![Screenshot 2024-10-30 145729](https://github.com/user-attachments/assets/5abc1cec-a8ce-46b9-ab01-e6e908ba2051)

**Comment by descentis** [comment]
You were not a collaborator for this repository. I have added you as a collaborator now. Please accept the invite and you should be able to push
